In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/trading/data.csv')

In [3]:
print(df.columns)
print(df.info())
df.head(10)

Index(['symbol', 'timeframe', 'time', 'open', 'high', 'low', 'close', 'volume',
       'adx', 'atr', 'bb_upper', 'bb_middle', 'bb_lower', 'cci', 'mfi', 'ma',
       'macd_main', 'macd_signal', 'obv', 'rsi', 'rvi', 'stddev', 'stoch_k',
       'stoch_d', 'willr', 'candle_type', 'zigzag_small', 'zigzag_large'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19768238 entries, 0 to 19768237
Data columns (total 28 columns):
 #   Column        Dtype
---  ------        -----
 0   symbol        object
 1   timeframe     object
 2   time          int64
 3   open          float64
 4   high          float64
 5   low           float64
 6   close         float64
 7   volume        int64
 8   adx           float64
 9   atr           float64
 10  bb_upper      float64
 11  bb_middle     float64
 12  bb_lower      float64
 13  cci           float64
 14  mfi           float64
 15  ma            float64
 16  macd_main     float64
 17  macd_signal   float64
 18  obv           int64
 19  rsi           float64
 20  rvi           float64
 21  stddev        float64
 22  stoch_k       float64
 23  stoch_d       float64
 24  willr         float64
 25  candle_type   int64
 26  zigzag_small  object
 27  zigzag_large  object
dtypes: float64(20), int64(4), object(4)
memory usage: 4.1+ GB
None

,symbol,timeframe,time,open,high,low,close,volume,adx,atr,...,obv,rsi,rvi,stddev,stoch_k,stoch_d,willr,candle_type,zigzag_small,zigzag_large
0,BTCUSDm,M1,1709182620,60420.42,60445.84,60363.97,60430.21,96,21.70,74.265714,...,3038036,53.09,0.0205,44.308307,40.66,52.50,-50.42,0,swing_low,NaN
1,BTCUSDm,M1,1709182980,60658.07,60698.43,60636.00,60698.43,135,33.60,73.047143,...,3038778,72.43,0.2440,87.130482,97.55,95.25,0.00,0,NaN,NaN
2,BTCUSDm,M1,1709183280,60837.69,60902.35,60828.32,60879.43,158,54.80,75.154286,...,3039297,78.48,0.4937,158.023831,88.18,87.84,-4.26,0,NaN,NaN
3,BTCUSDm,M1,1709183400,60892.57,60929.53,60857.91,60884.09,120,59.83,75.142143,...,3039332,77.24,0.5242,172.743027,79.25,84.33,-12.38,1,NaN,NaN
4,BTCUSDm,M1,1709183700,61027.09,61100.69,61018.80,61070.18,107,69.41,76.722857,...,3039852,83.94,0.4377,212.763900,87.70,89.62,-5.97,0,swing_high,NaN
5,BTCUSDm,M1,1709183880,61035.00,61067.50,60952.95,60952.95,114,63.57,87.756429,...,3039696,64.01,0.2045,176.827630,32.84,51.96,-34.67,1,NaN,NaN
6,BTCUSDm,M1,1709184000,60959.21,60959.95,60897.19,60916.37,91,54.15,82.635000,...,3039706,59.81,0.0652,137.023741,15.56,26.60,-61.93,1,NaN,NaN
7,BTCUSDm,M1,1709184240,61180.25,61215.89,61101.74,61187.68,158,49.26,95.773571,...,3040250,73.74,0.0950,111.132877,95.50,78.87,-8.53,0,NaN,NaN
8,BTCUSDm,M1,1709184480,61217.22,61303.55,61212.75,61286.02,131,55.43,99.950714,...,3040515,74.35,0.1638,112.670405,81.49,80.34,-4.19,0,NaN,NaN
9,BTCUSDm,M1,1709184600,61318.11,61321.20,61181.46,61206.60,123,55.86,98.042143,...,3040517,64.30,0.2848,117.759372,76.27,80.72,-27.02,1,NaN,NaN

In [4]:
df = df.drop(['time','zigzag_large','candle_type'], axis= 1)

In [5]:
print("Unique symbols:", df['symbol'].unique())
print("Unique timeframes:", df['timeframe'].unique())

Unique symbols: ['BTCUSDm' 'EURUSDm' 'USDJPYm' 'XAUUSDm' 'US30m']
Unique timeframes: ['M1' 'D1' 'H1' 'H4' 'M15' 'M30' 'M5']

In [6]:
grouped_dfs = {
    f"{symbol}_{tf}": group.reset_index(drop=True)
    for (symbol, tf), group in df.groupby(['symbol', 'timeframe'])
}

In [7]:
grouped_dfs.keys()

dict_keys(['BTCUSDm_D1', 'BTCUSDm_H1', 'BTCUSDm_H4', 'BTCUSDm_M1', 'BTCUSDm_M15', 'BTCUSDm_M30', 'BTCUSDm_M5', 'EURUSDm_D1', 'EURUSDm_H1', 'EURUSDm_H4', 'EURUSDm_M1', 'EURUSDm_M15', 'EURUSDm_M30', 'EURUSDm_M5', 'US30m_D1', 'US30m_H1', 'US30m_H4', 'US30m_M1', 'US30m_M15', 'US30m_M30', 'US30m_M5', 'USDJPYm_D1', 'USDJPYm_H1', 'USDJPYm_H4', 'USDJPYm_M1', 'USDJPYm_M15', 'USDJPYm_M30', 'USDJPYm_M5', 'XAUUSDm_D1', 'XAUUSDm_H1', 'XAUUSDm_H4', 'XAUUSDm_M1', 'XAUUSDm_M15', 'XAUUSDm_M30', 'XAUUSDm_M5'])

In [13]:
processed_dfs = {}
for key, sub_df in grouped_dfs.items():
    sub_df = sub_df.drop(columns=['symbol','timeframe'])

    total_len = len(sub_df)
    train_end = int(total_len * 0.8)  
    val_end = int(total_len * 0.9)     

    df_train = sub_df.iloc[:train_end].reset_index(drop=True)
    df_val   = sub_df.iloc[train_end:val_end].reset_index(drop=True)
    df_test  = sub_df.iloc[val_end:].reset_index(drop=True)

    target_col = 'zigzag_small'

    processed_dfs[key] = {
        'train': {'X': df_train.drop(columns=[target_col]), 'y': df_train[target_col]},
        'val'  : {'X': df_val.drop(columns=[target_col]),   'y': df_val[target_col]},
        'test' : {'X': df_test.drop(columns=[target_col]),  'y': df_test[target_col]},
    }